### ISSUE TITLE
Textures and vertex colors not shown on the model in Blender

### ISSUE THREAD

**Issue by Bri1101** [scurest/apicula#10]
I imported the dae file in Blender and when I textured the model, no vertex colors or textures were shown. What should I do?

**Comment by scurest** [comment]
Did you try setting the viewport shading to Material and turning World > Environment Lighting on?

![exampleb](https://user-images.githubusercontent.com/11024420/37693460-bf87a056-2c8d-11e8-837b-86ae8ae0233b.png)

**Comment by Bri1101** [comment]
Yes, and it gave me textures. The vertex colors are there, but I can't see them.

**Comment by scurest** [comment]
Yes, they don't influence the materials by default. I don't know a way to have the .dae say that they should. Did you see [this page](https://github.com/scurest/apicula/wiki/BLENDER#vertex-colors-dont-work) on the wiki?

I threw together a quick script to try to automatically add vertex color influence to all materials. Find it [here](https://gist.github.com/scurest/383b40dcf619cd19c7628bfdafa9fa6b). So save that file, and after you import your .dae, open Blender's text editor, open that file, and hit "Run Script" and the materials should all be influenced by vertex color.

**Comment by scurest** [comment]
I've added support for converting to [glTF](https://www.khronos.org/gltf/) instead of Collada. glTF has a better material model for representing NSBMD materials. You can convert to its `.glb` files with the `-f=glb` flag

    apicula c -f=glb <your files> -o <your output dir>

Then import the `.glb` into Blender with the [glTF-Blender-IO](https://github.com/KhronosGroup/glTF-Blender-IO) addon. (If you're using Blender 2.8, this might be installed by default.) When you look in the material view, you should be able to see the vertex colors.

![compare](https://user-images.githubusercontent.com/11024420/51784335-b1ee0100-210c-11e9-8a80-57539934b241.png)
