### ISSUE TITLE
extract to the same dir

### ISSUE THREAD

**Issue by Tosyk** [scurest/apicula#12]
Is it possible to extract files to the same dir?
I'd like to control files storing with cmd.

**Comment by scurest** [comment]
No, the directory always has to be fresh. You can just extract to a tempdir and then copy the files to wherever right?

**Comment by Tosyk** [comment]
I meant that I must to create new folders every time when I want to extract/convert anything. Is it possible to prevent this? creating new folder is a sctrict rule? I just don't feel good when tools forces me to spread unwanted folders through my hdd. Possibility to extract anywhere user wants would be a great feature.

**Comment by scurest** [comment]
Yes, it always creates a new folder. This is mainly so there's no question of conflicts with existing files.

**Comment by scurest** [comment]
When you say "same dir", you mean the current working directory?

**Comment by Tosyk** [comment]
I would rather have a note in a readme file that “any exported files could overwrite existent files with the same name” along with the option to export anywhere I want.

By “same die” I’ve meant same folder of source file. But option “to any specified folder” would be much flexible :)

**Comment by scurest** [comment]
I'm definitely not overwriting anything that's already on the disk. ConsoleTool does that when it extracts, which means extracting models with the same filename is harder. You also can't extract to the same dir as the input files since there can be more than one and they don't have to be in the same directory as each other.

So I still like creating a new directory. It's simple to code, simple to understand, and guaranteed not to clobber anything. You can easily script something to do things differently though, eg. this shell script will extract to the current dir clobbering existing files

````sh
tmp=`mktemp -du`
apicula extract $@ -o $tmp
for f in `ls $tmp`; do mv $tmp/$f .; done
rmdir $tmp
````

**Comment by Tosyk** [comment]
thanks for the script — I have something similar made for cmd. but I found this too much complex (create temp folder, extract resources to it, move resources from temp folder to source folder, remove temp folder) way to do such a simple task as extract a single model (and its textures). it's sad that you decided not to give that option to users.

**Comment by kr3nshaw** [comment]
Agreed - this is poor design.
