### ISSUE TITLE
Files from Sonic Rush, Rush Adventure, and Sonic Colors not properly working.

### ISSUE THREAD

**Issue by ShilzE01** [scurest/apicula#4]
![image](https://user-images.githubusercontent.com/30239690/28277438-f74931e8-6ae7-11e7-9aa1-d886f9a503ce.png)
Folders will be created, but they are empty.

**Comment by scurest** [comment]
Thanks for the bug report!

This is because the special texture transform modes are unimplemented. I pushed a change that should let you open the files but the texture coordinates on the models will probably be wrong. If you can upload one of the problematic NSBMD file for me to look at, I'll try to get this working.

**Comment by ShilzE01** [comment]
Okay, then. I haven't checked out the other games yet, but this should be good enough.
[sb_joh.zip](https://github.com/scurest/apicula/files/1157651/sb_joh.zip)

**Comment by scurest** [comment]
That model uses some render commands apicula doesn't recognize. After stubbing them in, the model seems to work. According to EveryFileExplorer, the missing command has something to do with environment mapping I guess?

See how it works with the new version.

![wild](https://user-images.githubusercontent.com/11024420/28347367-41af1c10-6bfc-11e7-82f5-eabbcdba2e5f.png)

**Comment by ShilzE01** [comment]
Worked like a charm! Thank you! Keep up the great work!

**Comment by scurest** [comment]
That's not an NSBMD file :) It's been compressed with LZ77. You're extremely lucky though: the extract command has rudimentary support for decompressing the DS's LZ77 files, which is enough for this case.

    $ ls
    boss7_body_lz7.nsbmd  boss7.nsbca
    $ apicula extract boss7_body_lz7.nsbmd -o tmp
    Found 1 BMD.
    Found 0 BTXs.
    Found 0 BCAs.
    $ mv tmp/* .
    $ rmdir tmp
    $ apicula convert boss7_body_00.nsbmd boss7.nsbca -o export

**Comment by ShilzE01** [comment]
Ah. That makes sense.
Anyways, that should be about it for now.

**Comment by Yarcaz** [comment]
Scurest, Hi & Hello. I am someone who Knows ShilzE01 and I am someone who has ripped from Sonic Adventure Rush before, in fact I have ripped every single model possible with MKDS, besides the ones that have errors. Shilz I see was able to chat with you to find a solution to some things but there are still some models from that game that I cannot seem to get and only recieve an error. I know that no matter what tools I have been using, whether it be NSMB editor, NSBMD Tools, Console Tools, MKDS Editor, Dirbaio, Tinke, or your program Apicula I have not been able to find a solution to getting the models from the specific few .nsbmd files from Sonic Rush adventure or Sonic Colors.

If you are ok with me asking... Can I post 2 links that lead to a download of the models that I could not rip from those games (Sonic Rush Adventure and Sonic Colors [DS]) here and see if you can find out why these certain models will not be ripped? (Sorry if this seems out of the blue.)

**Comment by scurest** [comment]
Hi Yarcaz.

The ones in the `README text file based errors/root/mod` directories (that you got `SHADOW` errors for?) look okay. The models with the error might be missing textures.

`Sonic Rush Adventure Models With Errors/WARNING text file based errors/root/mod/bossF*` doesn't work because the object section is missing, or is placed somewhere unusual. I can't find it in a hex editor. One thing you can try here is to play the game in Desmume until this model is onscreen, pause the game, take a memory dump, and then try running the memory dump through the extract command and see if you get anything out.

I don't have anything to extract NARC files right now, so I didn't check those.
