### ISSUE TITLE
"Couldn't find texture named ..."

### ISSUE THREAD

**Issue by MannedTooth** [scurest/apicula#7]
So I've been trying to extract models from The Legend of Zelda: Phantom Hourglass. I extracted everything into the same folder and add apicula to that folder as well. No matter the .nsbmd I'm trying to view, it always throws an exception that it couldn't find the texture.

`./apicula.exe view gd_boomerang`

`Found 1 model.
Found 0 animations.
ERROR:apicula::viewer::draw: error generating texture for material 0: Error(Msg("couldn\'t find texture named gd_Boomerang"), State { next_error: None, backtrace: None })`

**Comment by scurest** [comment]
It can't find it because the texture isn't in the NSBMD file. _Phantom Hourglass_ stores the textures in separate files from the models. In this case, the texture for `gd_boomerang.nsbmd` is in `gd_Boomerang.nsbtx` (filenames are assuming you extracted with `apicula extract`). You just need to add the NSBTX to the command invocation

    ./apicula.exe view gd_boomerang.nsbmd gd_Boomerang.nsbtx

If you can't guess what file the texture is in you can also just give apicula all of them and hope it finds it

    ./apicula.exe view gd_boomerang.nsbmd *.nsbtx

**Comment by scurest** [comment]
As of the latest version, this now prints a suggestion to add NSBTX files when this happens. We also now print the number of textures/palettes found, which should help too.

![examm](https://user-images.githubusercontent.com/11024420/36863409-36445e12-1d4f-11e8-9c62-858a6d27bda2.png)
