### ISSUE TITLE
The Sims 2 DS Corrupt Textures

### ISSUE THREAD

**Issue by KekMcGee** [scurest/apicula#8]
Textures come out super corrupt, or sometimes not at all like CreateASim.nsbmd they come out sometimes but are also corrupt even without using --more-textures which also doesn't work if used. https://mega.nz/#!thBGWTjJ!tKr7JB7Zo6K9Qc_3OrAM63WEEt_u4J79QEwbJBSedfo

**Comment by scurest** [comment]
Hm. Those definitely don't look right :)

The face that apicula crashes instead of reporting a proper error if it gets bad texture data is something I've meant to fix. There's a few other places that it can crash too.

The textures being garbage is more surprising. How did you extract them?

**Comment by KekMcGee** [comment]
Memory dump from Desmume and the extract function of apicula, the game's rom.bin archive is full of compressed files that nobody has figured out how to decompress yet, so this is the only way to get'em.

**Comment by scurest** [comment]
I mention this on the [EXTRACT](https://github.com/scurest/apicula/wiki/EXTRACT) page, but extracting from memory dumps frequently gives corrupt textures. I'd guess that after the texture data is uploaded to the GPU, it isn't kept around in RAM afterwards (the DS GPU doesn't store vertex data in GPU memory so that would explain why the model doesn't get messed up).

**Comment by KekMcGee** [comment]
Ah, alright. That's a shame, thanks.

**Comment by scurest** [comment]
This doesn't fix your textures, but the latest version should now not crash even if the textures are corrupt.
